#!/cluster/apps/r/3.6.0_openblas/x86_64/bin/Rscript
library("ggplot2")
library("hexbin")

## Usage: filter.visual.alignments.R <.assessment> <max.gapr> <min.nucd> <max.nucd> <min.alnl> <max.alnl> <min.pPIS> <max.pPIS>

## Author: Simon Crameri, ETHZ, Apr 2019 

## Get arguments
args = commandArgs(trailingOnly=TRUE)

## Check arguments
options(warning.length = 2000)
if (!length(args) %in% c(1, 8)) {
  stop("At least 1 argument needed:
       REQUIRED
       1) <table|CHR>: assessment input file generated by <assess.alignments.parallel.sh>. Header and tab-separation is expected. ;

       OPTIONAL (if any is given, all must be given in this order) (use 'FALSE' to specify that no filtering should be done)
       2) <max.gapr|NUM>: maximum gap ratio (number of gaps relative to the number of nucleotides) [default: 0.5] ;
       3) <min.nucd|NUM>: minimum average nucleotide diversity per site [default: 0] ;
       4) <max.nucd|NUM>: maximum average nucleotide diversity per site [default: 0.25] ;
       5) <min.alnl|NUM>: minimum alignment length [default: 100] ;
       6) <max.alnl|NUM>: maximum alignment length [default: FALSE] ;
       7) <min.pPIS|NUM>: minimum proportion of parsimony informative sites [default: FALSE] ;
       8) <max.pPIS|NUM>: maximum proportion of parsimony informative sites [default: FALSE]", 
       call.=FALSE)
}

## Set arguments
set.argument <- function(string,
                         nullstrings = c("null", "NULL", "Null"),
                         nastrings = c("na", "NA", "Na"), 
                         truestrings = c("T", "TRUE", "t", "true", "True"),
                         falsestrings = c("F", "FALSE", "f", "false", "False"),
                         type = "character") {
  
  stopifnot(type %in% c("numeric", "character"))
  
  # determine whether it is TRUE, FALSE or NA
  if (string %in% nullstrings) isnull <- TRUE else isnull <- FALSE
  if (string %in% nastrings) isna <- TRUE else isna <- FALSE
  if (string %in% truestrings) true <- TRUE else true <- FALSE
  if (string %in% falsestrings) false <- TRUE else false <- FALSE
  
  # set argument
  if (isnull) arg <- NULL
  if (isna) arg <- NA
  if (true) arg <- TRUE
  if (false) arg <- FALSE
  if (!isnull & !isna & !true & !false) {
    switch(type,
           numeric = {arg <- as.numeric(string)},
           character = {arg <- as.character(string)}
    )
  }
  return(arg)
}

table = set.argument(args[1])

max.gapr = set.argument(args[2], type = "numeric")
if (is.na(max.gapr)) max.gapr <- 0.5
min.nucd = set.argument(args[3], type = "numeric")
if (is.na(min.nucd)) min.nucd <- 0
max.nucd = set.argument(args[4], type = "numeric")
if (is.na(max.nucd)) max.nucd <- 0.25
min.alnl = set.argument(args[5], type = "numeric")
if (is.na(min.alnl)) min.alnl <- 100
max.alnl = set.argument(args[6], type = "numeric")
if (is.na(max.alnl)) max.alnl <- FALSE
min.pPIS = set.argument(args[7], type = "numeric")
if (is.na(min.pPIS)) min.pPIS <- FALSE
max.pPIS = set.argument(args[8], type = "numeric")
if (is.na(max.pPIS)) max.pPIS <- FALSE


## Set arguments (for debugging)
# table = "test.assess.txt"
# max.gapr = F
# min.nucd = F
# max.nucd = F
# min.alnl = 100
# max.alnl = FALSE
# min.pPIS = F
# max.pPIS = F
args <- c

## Additional arguments
nbins = 50
margins = c(0.5,1,0.5,0.5) # plot margins (top, right, bottom, left) in cm

## Check arguments
stopifnot(file.exists(table),
          any(isFALSE(max.gapr), max.gapr >= 0, max.gapr <= 1),
          any(isFALSE(min.nucd), min.nucd >= 0, min.nucd <= 1),
          any(isFALSE(max.nucd), max.nucd >= 0, max.nucd <= 1),
          any(isFALSE(min.alnl), min.alnl >= 0),
          any(isFALSE(max.alnl), max.alnl >= 0),
          any(isFALSE(min.pPIS), min.pPIS >= 0, min.pPIS <= 1),
          any(isFALSE(max.pPIS), max.pPIS >= 0, max.pPIS <= 1))
if (is.numeric(min.nucd) & is.numeric(max.nucd)) stopifnot(min.nucd <= max.nucd)
if (is.numeric(min.alnl) & is.numeric(max.alnl)) stopifnot(min.alnl <= max.alnl)
if (is.numeric(min.pPIS) & is.numeric(max.pPIS)) stopifnot(min.pPIS <= max.pPIS)

## Define helperfunctions
# filter
filterby <- function(df, var, thresh, type = "max") {
  stopifnot(is.data.frame(df), 
            is.character(var), var %in% names(df),
            is.numeric(df[,var]),
            any(is.numeric(thresh), is.logical(thresh)),
            type %in% c("min", "max"))
  if (is.numeric(thresh)) {
    switch(type,
           min = {
             df.sub <- df[df[,var] >= thresh,]
           },
           max = {
             df.sub <- df[df[,var] <= thresh,]
           }
    )
  } else {
    df.sub <- df
  }
  return(df.sub)
}

# plot
hexplot <- function(df, nbins = 50, x = "ngpernuctot", y = "avgnucdivpersite", z = "avgnucdivpersite", 
                    xlab = "Gap ratio", ylab = "Average nucleotide diversity per site", zlab = "Count",
                    legend.position = "top", plot.margin = unit(c(0.5, 1, 0.5, 0.5), "cm"),
                    FUN = length, print = TRUE) {
  p <- ggplot(df, aes_string(x = x, y = y, z = z)) +
    stat_summary_hex(bins = nbins, fun = function(x) do.call(FUN, list(x))) +
    xlab(xlab) +
    ylab(ylab) +
    scale_fill_continuous(name = zlab) +
    theme_bw() +
    theme(legend.position = legend.position, plot.margin = plot.margin)
  if (print) print(p)
  invisible(p)
}

# shorten argument strings for output file name
shorten <- function(x) {
  if (is.null(x)) {
    name <- "NULL"
  } else {
    if (is.character(x)) name <- x
    if (is.numeric(x)) {if (x < 1) {name <- round(x,2)} else {name <- x}}
    if (is.logical(x)) name <- substring(as.character(x), 1, 1)
    if (is.na(x)) name <- "NA"
  }
  return(as.character(name))
}

############################################################################

## Prepare data.frame
d.filter <- read.delim(table)
stopifnot(all(c("ngtot","ngpernuctot","nuctotdiversity","avgnucdivpersite",
                "gc","length","nSEG","pSEG","nPIS","pPIS","file") %in% names(d.filter)))
rownames(d.filter) <- seq(nrow(d.filter))

## Filter
d.passed <- d.filter
d.passed <- filterby(d.passed, "ngpernuctot", max.gapr, "max")
d.passed <- filterby(d.passed, "avgnucdivpersite", min.nucd, "min")
d.passed <- filterby(d.passed, "avgnucdivpersite", max.nucd, "max")
d.passed <- filterby(d.passed, "length", min.alnl, "min")
d.passed <- filterby(d.passed, "length", max.alnl, "max")
d.passed <- filterby(d.passed, "pPIS", min.pPIS, "min")
d.passed <- filterby(d.passed, "pPIS", max.pPIS, "max")

d.excluded <- d.filter[!rownames(d.filter) %in% rownames(d.passed),]

## Plot
pdf(file = paste0(gsub(".txt$", "", table), ".pdf"), width = 7, height = 7)


basepl <- hexplot(d.filter, nbins, z = "avgnucdivpersite", zlab = "Count", FUN = length, print = FALSE)
if (is.numeric(max.gapr)) basepl <- basepl + geom_vline(aes(xintercept = max.gapr))
if (is.numeric(min.nucd)) basepl <- basepl + geom_hline(aes(yintercept = min.nucd))
if (is.numeric(max.nucd)) basepl <- basepl + geom_hline(aes(yintercept = max.nucd))

print(basepl)
hexplot(d.filter, nbins, z = "ngtot", zlab = "Number of gaps", FUN = mean)
hexplot(d.filter, nbins, z = "nuctotdiversity", zlab = "Total nucleotide diversity", FUN = mean)
hexplot(d.filter, nbins, z = "gc", zlab = "GC content", FUN = mean)
hexplot(d.filter, nbins, z = "length", zlab = "Alignment length", FUN = mean)
# hexplot(d.filter, nbins, z = "nSEG", zlab = "Number of polymorphic sites", FUN = mean)
hexplot(d.filter, nbins, z = "pSEG", zlab = "Proportion of polymorphic sites", FUN = mean)
# hexplot(d.filter, nbins, z = "nPIS", zlab = "Number of parsimony informative sites", FUN = mean)
hexplot(d.filter, nbins, z = "pPIS", zlab = "Proportion of parsimony informative sites", FUN = mean)

graphics.off()

## Write output
cat(paste0("\nNumber of retained loci: ", nrow(d.passed), " (", round(100*nrow(d.passed)/nrow(d.filter), 2), "%)\n"))
cat(paste0("Number of loci to exclude: ", nrow(d.excluded), " (", round(100*nrow(d.excluded)/nrow(d.filter), 2), "%)\n\n"))

outstring <- unlist(lapply(list(max.gapr, min.nucd, max.nucd, min.alnl, max.alnl, min.pPIS, max.pPIS), FUN = shorten))
oname <- paste(gsub(".txt$", "", table), paste(outstring, collapse = "-"), "txt", sep = ".")
write.table(sort(basename(as.character(d.excluded$file))),
            file = oname,
            row.names = F, col.names = F, quote = F)

